title: Belkirk College of Engineering
short_title: Belkirk
description: Jekyll demo for Forestry CMS
baseurl:
permalink: "/:path/"
include: ['_pages']
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
    permalink: "/:year-:month-:day-:title/"
  projects:
    output: true
    permalink: "/projects/:path/"
  category:
    output: true
  en:
    output: true
    permalink: "/en/_path/"
  hr:
    output: true
    permalink: "/hr/_posts/"
  cz:
    output: true
    permalink: "/cz/_posts/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
plugins:
  - jekyll-feed
  - jekyll-archives
