---
new_page_extension: md
auto_deploy: false
admin_path: admin-editor
webhook_url: 
sections:
- type: heading
  label: Content
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: heading
  label: Czech Posts
- type: directory
  path: cz/_posts
  label: Posts
  create: all
  match: "**/*"
- type: heading
  label: English
- type: directory
  path: en
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: en/_posts
  label: Posts
  create: all
  match: "**/*"
- type: heading
  label: Croatian
- type: directory
  path: hr
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: hr/_posts
  label: Posts
  create: all
  match: "**/*"
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
